configuration:
  properties:
    # It isn't necessary to define this property as it is generated, if missing.
    MIRROR_CONFIG: /app/server-map.json

  existingServerMap:
    # The name of the ConfigMap object.
    configmap: mirror-app-server-config
    # Key in the ConfigMap object that holds the JSON content.
    configmapKey: server-map.json
    # The path where the server map JSON file will be mounted.
    mountPath: /app/server-map.json
