apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphviews.fullname.configmap.environment" . }}
  namespace: {{ include "graphviews.namespace" . }}
  labels:
    {{- include "graphviews.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  JAVA_TOOL_OPTIONS: >-
    {{ tpl .Values.configuration.defaultJavaArguments . }}
    {{ tpl .Values.configuration.javaArguments . }}
