apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphviews.fullname" . }}
  namespace: {{ include "graphviews.namespace" . }}
  labels:
    {{- include "graphviews.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  selector:
    matchLabels:
      {{- include "graphviews.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graphviews.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if or .Values.configuration.properties .Values.configuration.existingServerMap.configmap }}
        checksum/config-properties: {{ include (print $.Template.BasePath "/config-properties.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.configuration.gunicornArguments }}
        checksum/configmap-environment: {{ include (print $.Template.BasePath "/configmap-environment.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "graphviews.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if or .Values.global.imagePullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "graphviews.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {{ .Values.tempVolume.emptyDir | toYaml | nindent 12 }}
      {{- if .Values.configuration.existingServerMap.configmap }}
        - name: {{ .Values.configuration.existingServerMap.configmap }}
          configMap:
            name: {{ .Values.configuration.existingServerMap.configmap }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "graphviews.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.http }}
              protocol: TCP
          {{- with .Values.extraContainerPorts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.configuration.propertiesOverrides.existingConfigmap }}
            - configMapRef:
                name: {{ .Values.configuration.propertiesOverrides.existingConfigmap }}
            {{- else }}
            - configMapRef:
                name: {{ include "graphviews.fullname.configmap.properties" . }}
            {{- end }}
            {{- if .Values.configuration.existingSecret }}
            - secretRef:
                name: {{ .Values.configuration.existingSecret }}
            {{- end }}
            - configMapRef:
                name: {{ include "graphviews.fullname.configmap.environment" . }}
            {{- with .Values.extraEnvFrom }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnv }}
          env: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          {{- if .Values.configuration.existingServerMap.configmap }}
            - name: {{ .Values.configuration.existingServerMap.configmap }}
              mountPath: {{ .Values.configuration.existingServerMap.mountPath }}
              subPath: {{ .Values.configuration.existingServerMap.configmapKey }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
