{{- if not .Values.configuration.propertiesOverrides.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semantic-workbench.fullname.configmap.properties" . }}
  namespace: {{ include "semantic-workbench.namespace" . }}
  labels:
    {{- include "semantic-workbench.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $val := .Values.configuration.properties -}}
    {{- if ne $val nil }}
      {{- $key | nindent 2 }}: {{ tpl ($val | toString) $ | quote }}
    {{- end }}
  {{- end -}}
{{ end }}
