{{- if .Values.ingress.enabled }}
{{- $external_url := urlParse (include "mirror-app.external-url" .) -}}
{{- $host_parts := split ":" $external_url.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mirror-app.fullname" . }}
  namespace: {{ include "mirror-app.namespace" . }}
  labels:
    {{- include "mirror-app.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.ingress.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if or .Values.ingress.tls.enabled .Values.ingress.extraTLS }}
  tls:
    {{- if .Values.ingress.tls.enabled }}
    - hosts:
        - {{ coalesce .Values.ingress.host $host_parts._0 }}
      secretName: {{ required "TLS secret is required!" .Values.ingress.tls.secretName }}
    {{- end }}
    {{- with .Values.ingress.extraTLS }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ coalesce .Values.ingress.host $host_parts._0 }}
      http:
        paths:
          - path: {{ coalesce .Values.ingress.path $external_url.path "/" }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "mirror-app.fullname" . }}
                port:
                  number: {{ .Values.service.ports.http }}
    {{- with .Values.ingress.extraHosts }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
